ARG eddl_rev
FROM simleo/eddl:${eddl_rev}

RUN apt-get -y update && apt-get -y install --no-install-recommends \
      python3-dev \
      python3-pip && \
    python3 -m pip install --upgrade --no-cache-dir \
      setuptools \
      pip \
      numpy \
      pybind11 \
      pytest

RUN mkdir -p /home/simleo && \
    groupadd -r -g 1000 simleo && \
    useradd -lr -u 1000 -g 1000 simleo && \
    chown -R simleo:simleo /home/simleo

ENV HOME=/home/simleo

USER simleo
