FROM stal12/cuda10-gcc5

COPY third_party/eddl /eddl
WORKDIR /eddl

RUN apt-get -y update && apt-get -y install --no-install-recommends \
    zlib1g-dev

RUN mkdir build && \
    cd build && \
    ln -s /usr/lib/x86_64-linux-gnu/libcublas.so /usr/local/cuda/lib64/ && \
    cmake -D BUILD_TARGET=GPU -D BUILD_TESTS=ON -D EDDL_SHARED=ON .. && \
    make -j$(grep -c ^processor /proc/cpuinfo) && \
    make install
