FROM crs4/cmake:3.14

RUN apt-get -y update && apt-get -y install --no-install-recommends \
    build-essential \
    ca-certificates \
    wget \
    zlib1g-dev

COPY third_party/eddl /eddl
WORKDIR /eddl

RUN mkdir build && \
    cd build && \
    cmake -D BUILD_TESTS=ON -D EDDL_SHARED=ON .. && \
    make -j$(grep -c ^processor /proc/cpuinfo) && \
    make install
