FROM nvidia/cuda:10.1-devel

RUN apt-get -y update && apt-get -y install wget && \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local && \
    conda update conda && \
    conda install conda-build && \
    conda update conda-build

COPY eddl /eddl

RUN conda build eddl
