#include <eddl/utils.h>
#include <eddl/tensor/tensor.h>
#include <eddl/descriptors/descriptors.h>
#include <eddl/tensor/nn/tensor_nn.h>
#include <eddl/compserv.h>
#include <eddl/losses/loss.h>
#include <eddl/metrics/metric.h>
#include <eddl/layers/layer.h>
#include <eddl/layers/core/layer_core.h>
#include <eddl/layers/conv/layer_conv.h>
#include <eddl/layers/pool/layer_pool.h>
#include <eddl/layers/noise/layer_noise.h>
#include <eddl/layers/merge/layer_merge.h>
#include <eddl/layers/reductions/layer_reductions.h>
#include <eddl/optimizers/optim.h>
#include <eddl/net.h>
#include <dummy.hpp>
