FROM continuumio/miniconda3

RUN conda update conda && \
    conda install conda-build && \
    conda update conda-build

# dhealth/linux-64 must contain the eddl-gpu conda package
COPY dhealth /channels/dhealth
RUN conda index /channels/dhealth/

COPY pyeddl /pyeddl
RUN conda build -c file://channels/dhealth pyeddl
