FROM continuumio/miniconda3

RUN conda update conda && \
    conda install conda-build && \
    conda update conda-build

# dhealth/linux-64 must contain the eddl-cpu conda package
COPY dhealth /dhealth

RUN conda index /dhealth/ && \
    conda create -y -n eddl-test && \
    conda install -y -n eddl-test -c file://dhealth eddl-cpu

COPY test.sh /test.sh
