FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

RUN for v in 3.6 3.7 3.8; do \
      conda create -y -n test${v} python=${v} && \
      conda install -y -n test${v} -c dhealth pyeddl-cpu; \
    done

# expects pyeddl tests in "tests"
COPY tests /tests
COPY test_pyeddl.sh /test.sh
