FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

# dhealth/linux-64 must contain the eddl-cpu conda package
COPY dhealth /channels/dhealth
RUN conda index /channels/dhealth/

COPY pyeddl /pyeddl
RUN conda build -c file://channels/dhealth pyeddl
