FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

RUN conda create -y -n eddl-test && \
    conda install -y -n eddl-test -c dhealth eddl-cpu

COPY test_eddl.sh /test.sh
