FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

# dhealth/linux-64 must contain the eddl-cpu conda package
COPY dhealth /dhealth

RUN conda index /dhealth/ && \
    conda create -y -n eddl-test && \
    conda install -y -n eddl-test -c file://dhealth eddl-cpu

COPY test_eddl.sh /test.sh
