FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

# dhealth/linux-64 must contain the eddl-cpu and pyeddl-cpu conda packages
COPY dhealth /channels/dhealth

RUN conda index /channels/dhealth/ && \
    conda create -y -n test && \
    conda install -y -n test -c file://channels/dhealth pyeddl-cpu

# expects pyeddl tests in "tests"
COPY tests /tests
COPY test_pyeddl.sh /test.sh
