FROM dhealth/dev-pyeddl-base-gpu

ENV EDDL_WITH_CUDA="true"

RUN for l in cudart curand cublas; do \
      ln -s /usr/local/cuda-10.1/targets/x86_64-linux/lib/lib${l}.so /usr/lib/; \
    done

COPY . /pyeddl
WORKDIR /pyeddl

RUN python3 setup.py install
