FROM continuumio/miniconda3

RUN conda update conda && \
    conda install conda-build && \
    conda update conda-build

COPY eddl /eddl

RUN conda config --set channel_priority strict && \
    conda build -c conda-forge eddl
