FROM nvidia/cuda:10.1-runtime

ENV PATH="/opt/conda/bin:${PATH}"

RUN apt-get -y update && apt-get -y install wget && \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && \
    conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

RUN for v in 3.6 3.7 3.8; do \
      conda create -y -n test${v} python=${v} && \
      conda install -y -n test${v} -c dhealth pyeddl-gpu; \
    done && \
    conda init bash

# expects pyeddl tests in "tests"
COPY tests /tests
COPY test_pyeddl.sh /test.sh
