FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

COPY eddl /eddl

RUN conda config --set channel_priority strict && \
    conda build -c conda-forge eddl
