name: test

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build eddl image
        run: docker build -t eddl -f Dockerfile.eddl .
      - name: build pyeddl image
        run: docker build -t pyeddl .
      - name: run tests
        run: docker run --rm pyeddl bash -c "pytest tests"
      - name: install build dependencies
        run: python -m pip install --upgrade setuptools
      - name: build
        run: python setup.py sdist
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
