name: test

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build eddl image
        run: docker build -t eddl -f Dockerfile.eddl .
      - name: build pyeddl image
        run: docker build -t pyeddl .
      - name: run tests
        run: docker run --rm pyeddl bash -c "pytest tests"
